# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Code Review Automation with Language Models
author: Alexander Kovrigin
copyright: "2023"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/waleko/Code-Review-Automation-LM  # Online location of your book
  branch: gh-pages  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
